### ISSUE TITLE
Rearrange graphs for better comparison in Figure 7 of paper

### ISSUE THREAD

**Issue by wverastegui** [RECETOX/ei_spectra_predictions#32]
Currently, in Figure 7 on Page 14 of the paper (https://chemrxiv.org/engage/chemrxiv/article-details/65fd8fc09138d2316107fbb6), it's difficult to compare the effects of nitrogen addition to compounds. To enhance clarity:
The python script that creates Figure 7 is : https://github.com/RECETOX/ei_spectra_predictions/blob/main/analysis/Python_scripts/chemical_composition_boxplot.ipynb
- Align the "without N" and "with N" bars for each class side by side.
- Divide the data into "ions matching reference" and "scores" subfigures for clearer organization.

**Comment by hechth** [comment]
This is done now :)
